# Site settings
title: Smart Material Theme
email: your-email@domain.com
description: Slick Material Design theme for Jekyll powered by Material Design Lite.
baseurl: "/jekyll-smart-material" # the subpath of your site, e.g. /blog/
url: "http://ssokurenko.github.io" # the base hostname & protocol for your site
copyright: '&copy; 2015 Smart Material Theme'
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
